baseURL = "https://bts.antoinespiteri.net"
languageCode = "en-us"
theme = "adritian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "À propos"
  URL = "#about"
  weight = 2

  # [[menu.header]]
  # name = "Portfolio"
  # URL = "#portfolio"
  # weight = 3

  [[menu.header]]
  name = "Experiences"
  URL = "/experience"
  weight = 4

  [[menu.header]]
  identifier = "epreuves"
  name = "E5/E6"
  URL = "/epreuves"
  weight = 5

  [[menu.header]]
  name = "Veille technologiques"
  URL = "/blog"
  weight = 6

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 7

  [[menu.footer]]
  name = "À propos"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Experiences"
  URL = "/experience"
  weight = 3

  [[menu.footer]]
  identifier = "epreuves"
  name = "E5/E6"
  URL = "/epreuves"
  weight = 4

  [[menu.footer]]
  name = "Veille technologiques"
  URL = "/blog"
  weight = 5

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 6


[params]

  sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]

  homepageExperienceCount = 6

  # controls vercel page insights - disabled by default
  vercelPageInsights = false
  vercelAnalytics = false
  
  [params.google_analytics]
      code = "UA-XXXXX-Y"
      enabled = false
  [params.google_tag_manager]
      code = "GTM-XXXXX"
      enabled = false
  
  [params.logo]
    text1 = "Antoine"
    text2 = " SPITERI"

  [params.footer]
      copyright = "© Antoine SPITERI. Thème par Adrián Moreno Peña."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"


